jaffle_shop:
  outputs:
    dev:
      type: snowflake
      account: ADMIRALPIONEER-TOOLBOX
      user: sandbox
      private_key: "{{ env_var('SNOWFLAKE_PRIVATE_KEY') }}"
      role: sandbox_admin
      warehouse: sandbox_wh
      database: sandbox_db
      schema: dev
      threads: 1
    prod:
      type: snowflake
      account: ADMIRALPIONEER-TOOLBOX
      user: sandbox
      private_key: "{{ env_var('SNOWFLAKE_PRIVATE_KEY') }}"
      role: sandbox_admin
      warehouse: sandbox_wh
      database: sandbox_db
      schema: prod
      threads: 1
  target: dev
